name: Test Build

on:
  workflow_dispatch:
  push:

env:
  token_listrik: ${{ secrets.TOKEN_PLN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anggit86/docker:ubuntu
    permissions:
      contents: write
    steps:
    # You might want to Checkout your repo first, but not mandatory
    # - name: Check Out
      # uses: actions/checkout@v4

    # - name: Prepare the environment
      # run: |
        # apt-get -y install bison build-essential curl flex git git-core gnupg gperf libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk2.8-dev libxml2 libxml2-utils lzop openjdk-7-jdk openjdk-7-jre pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev unzip lib32readline-gplv2-dev lib32z1-dev make python python-networkx zlib1g-dev:i386 phablet-tools

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir patchrom
        cd patchrom
        git config --global user.name "UntuKemeng"
        git config --global user.email "jarbull87@gmail.com"
        repo init -u https://github.com/MiCode/patchrom.git -b marshmallow

    - name: Repo Sync
      run: |
        cd patchrom
        repo sync -j$(nproc --all)

    # - name: Set Swap Space
      # uses: pierotofy/set-swap-space@master
      # with:
        # swap-size-gb: 12

    - name: Clone stockrom
      run: |
        cd patchrom
        git clone https://UntuKemeng:${token_listrik}@github.com/UntuKemeng/ssj2p
        cd ssj2p && wget -O stockrom.zip https://ylsd7-my.sharepoint.com/personal/pikachu_ylsd7_onmicrosoft_com/_layouts/15/download.aspx?share=EcV39Q5Q9nVNkKChM07DJIgB3pcOah2usc9UHHMk4eKNtQ
        git reset --hard 1a67b20

    - name: Test
      run: |
        cd patchrom
        . build/envsetup.sh
        cd ssj2p
        make workspace
        # make firstpatch

    - name: Push
      run: |
        cd patchrom/ssj2p
        rm -rf stockrom.zip
        git add . -f
        git commit -m "Add fw jar"
        git push -f origin
