name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v4

    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps

    - name: Prepare the environment
      run: |
        sudo apt -y update && sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses* python3

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Setup SSH Keys
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') || 
          startsWith(github.event.inputs.DEVICE_TREE_URL, 'git@github.com') ||
          startsWith(github.event.inputs.COMMON_TREE_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo
      run: |
        sudo su
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        sudo su
        mkdir LineageOS
        cd LineageOS
        echo "LineageOS-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "AnGgIt86"
        git config --global user.email "jarbull86@gmail.com"
        repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android -b cm-14.1 -g default,-mips,-darwin,-notdefault
      id: pwd

    - name: Repo Sync
      run: |
        sudo su
        git clone https://github.com/UWU-TEAM/local_manifests_grandppltedx --depth 1 -b main .repo/local_manifests
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
      working-directory: LineageOS

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building
      run: |
       sudo su
        export ALLOW_MISSING_DEPENDENCIES=true
        export LANG=C.UTF-8
        export LC_ALL=C
        export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx120G"
        export JAVA_OPTS=" -Xmx120G "
        source build/envsetup.sh
        lunch lineage_grandppltedx-userdebug
        export TZ=Asia/Jakarta
        export BUILD_USERNAME=grandpplte
        export BUILD_HOSTNAME=nfsproject
        brunch grandppltedx
      working-directory: ${{ steps.pwd.outputs.LineageOS-folder }}
